name: CI
on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 3 * * *'
  workflow_dispatch:

jobs:
  fetch:
    name: Fetch package data
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
      - name: Install dependencies
        run: |
          dnf -y install koji copr-cli dnf-utils fedora-packager git python3-bugzilla
      - name: Get source
        uses: actions/checkout@v4
      - name: Set up Copr & Koji repo
        run: |
          cp ./config/copr.repo /etc/yum.repos.d/copr.repo
          cp ./config/koji.repo /etc/yum.repos.d/koji.repo
      - name: Run repoquery
        run: |
          chmod +x ./scripts/run.sh
          ./scripts/run.sh
      - name: Commit and push
        run: |-
          git config --global --add safe.directory /__w/fedora-python-rebuild-status/fedora-python-rebuild-status
          git config user.name "Beep boop"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
  publish:
    name: Populate gh-pages
    needs: fetch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Freeze site
        run: python -m freezeyt app _build --prefix https://befeleme.github.io/fedora-python-rebuild-status/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build
